from configs.linear_scale10 import get_config as get_linear_config


def get_config():
  """Linear model whose direction-dependent matrix is generated by an MLP."""
  config = get_linear_config()
  config.model.trans_type = 'linear_polar_mlp'
  config.model.trans_hidden_size = 128
  config.model.trans_num_hidden_layers = 2
  return config
